# Generated by Django 4.1 on 2022-11-09 02:22

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='商品名')),
                ('image', models.ImageField(upload_to='', verbose_name='商品图片')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('intro', models.TextField(max_length=1000, verbose_name='商品描述')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='', max_length=256, verbose_name='地址')),
                ('license', models.ImageField(height_field=20, upload_to='', verbose_name='商家执照', width_field=15)),
                ('logo', models.ImageField(blank=True, height_field=20, upload_to='', verbose_name='店铺头像', width_field=15)),
                ('info', models.TextField(max_length=1000, verbose_name='商铺描述')),
                ('star', models.FloatField(default=5, verbose_name='星级')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('isChecked', models.BooleanField(default=False, verbose_name='是否通过审核')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='', max_length=256, verbose_name='地址')),
                ('card_num', models.CharField(max_length=30, verbose_name='银行卡号')),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Takeout.store', verbose_name='店铺')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Takeout.user', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.date.today, verbose_name='注册时间')),
                ('isPass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takeout.store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='订单时间')),
                ('address', models.CharField(max_length=256, verbose_name='订单配送地点')),
                ('isProcessed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('isDelivered', models.BooleanField(default=False, verbose_name='是否已送达')),
                ('belonging_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Takeout.store')),
                ('belonging_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Takeout.user')),
                ('items', models.ManyToManyField(to='Takeout.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='belonging_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takeout.store'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.date.today, verbose_name='预计送达时间')),
                ('fee', models.FloatField(default=5, verbose_name='骑手小费')),
                ('isOnTime', models.BooleanField(default=True, verbose_name='是否按时送达')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takeout.order')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=1000, verbose_name='评价')),
                ('star', models.IntegerField(default=5, verbose_name='星级')),
                ('time', models.DateField(default=datetime.date.today, verbose_name='评论时间')),
                ('image', models.ImageField(height_field=8, upload_to='', verbose_name='评论图片', width_field=8)),
                ('belonging_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Takeout.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takeout.store')),
                ('belonging_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Takeout.user')),
                ('items', models.ManyToManyField(to='Takeout.item')),
            ],
        ),
    ]
