# Generated by Django 3.2.16 on 2022-11-24 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Takeout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cookie',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 12, 14, 37, 442756, tzinfo=utc), max_length=20, unique=True, verbose_name='店铺名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 12, 14, 46, 802391, tzinfo=utc), max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
