# Generated by Django 4.1 on 2022-11-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Takeout', '0001_initial'),
        ('Takeout', '0002_auto_20221124_2014'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cookie',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 11, 43, 50, 188353, tzinfo=datetime.timezone.utc), max_length=20, unique=True, verbose_name='店铺名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2022, 11, 24, 11, 44, 0, 56247, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]